apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnsi-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-native-security-inspector-portal-serviceaccount
  namespace: {{ .Release.Namespace }}
---
