# Default values for cnsi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "projects.registry.vmware.com/cnsi"
  # override image tag, which is .Chart.AppVersion by default
  tag: "0.3"
  pullPolicy: "IfNotPresent"

opensearch:
  persistence:
    enabled: false