// Copyright 2022 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0
// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AssessmentResponse assessment response
//
// swagger:model AssessmentResponse
type AssessmentResponse struct {

	// details
	Details []*Details `json:"details"`

	// enforcements
	Enforcements []*Enforcement `json:"enforcements"`

	// passed
	Passed bool `json:"passed,omitempty"`

	// total
	Total int32 `json:"total,omitempty"`

	// vulnerable
	Vulnerable int32 `json:"vulnerable,omitempty"`
}

// Validate validates this assessment response
func (m *AssessmentResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnforcements(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AssessmentResponse) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(m.Details) { // not required
		return nil
	}

	for i := 0; i < len(m.Details); i++ {
		if swag.IsZero(m.Details[i]) { // not required
			continue
		}

		if m.Details[i] != nil {
			if err := m.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AssessmentResponse) validateEnforcements(formats strfmt.Registry) error {

	if swag.IsZero(m.Enforcements) { // not required
		return nil
	}

	for i := 0; i < len(m.Enforcements); i++ {
		if swag.IsZero(m.Enforcements[i]) { // not required
			continue
		}

		if m.Enforcements[i] != nil {
			if err := m.Enforcements[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("enforcements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AssessmentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssessmentResponse) UnmarshalBinary(b []byte) error {
	var res AssessmentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
