// Copyright 2022 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0
// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"net/url"

	"github.com/go-openapi/runtime"
	rtclient "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/rest/client/assessment"
	"github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/rest/client/operations"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:9090"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

type Config struct {
	// URL is the base URL of the upstream server
	URL *url.URL
	// Transport is an inner transport for the client
	Transport http.RoundTripper
	// AuthInfo is for authentication
	AuthInfo runtime.ClientAuthInfoWriter
}

// New creates a new CNSI HTTP client.
func New(c Config) *CNSIAPIs {
	var (
		host     = DefaultHost
		basePath = DefaultBasePath
		schemes  = DefaultSchemes
	)

	if c.URL != nil {
		host = c.URL.Host
		basePath = c.URL.Path
		schemes = []string{c.URL.Scheme}
	}

	transport := rtclient.New(host, basePath, schemes)
	if c.Transport != nil {
		transport.Transport = c.Transport
	}

	cli := new(CNSIAPIs)
	cli.Transport = transport
	cli.Assessment = assessment.New(transport, strfmt.Default, c.AuthInfo)
	cli.Operations = operations.New(transport, strfmt.Default, c.AuthInfo)
	return cli
}

// CNSIAPIs is a client for k s i a p is
type CNSIAPIs struct {
	Assessment *assessment.Client
	Operations *operations.Client
	Transport  runtime.ClientTransport
}
