// Copyright 2022 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0
// Code generated by go-swagger; DO NOT EDIT.

package assessment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/rest/models"
)

// ListNamespacesReader is a Reader for the ListNamespaces structure.
type ListNamespacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListNamespacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListNamespacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListNamespacesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListNamespacesOK creates a ListNamespacesOK with default headers values
func NewListNamespacesOK() *ListNamespacesOK {
	return &ListNamespacesOK{}
}

/*
ListNamespacesOK handles this case with default header values.

successful operation
*/
type ListNamespacesOK struct {
	Payload []*models.NSWithPolicies
}

func (o *ListNamespacesOK) Error() string {
	return fmt.Sprintf("[GET /namespaces][%d] listNamespacesOK  %+v", 200, o.Payload)
}

func (o *ListNamespacesOK) GetPayload() []*models.NSWithPolicies {
	return o.Payload
}

func (o *ListNamespacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNamespacesInternalServerError creates a ListNamespacesInternalServerError with default headers values
func NewListNamespacesInternalServerError() *ListNamespacesInternalServerError {
	return &ListNamespacesInternalServerError{}
}

/*
ListNamespacesInternalServerError handles this case with default header values.

Internal server error occurred
*/
type ListNamespacesInternalServerError struct {
}

func (o *ListNamespacesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /namespaces][%d] listNamespacesInternalServerError ", 500)
}

func (o *ListNamespacesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
