# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
# Build the manager binary
FROM projects.registry.vmware.com/cnsi/golang:1.19 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

# Copy the go source
COPY ./ .
RUN mkdir -p /home/scanner/.cache

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o trivy cnsi-scanner-trivy/cmd/scanner-trivy/main.go

# FROM projects.registry.vmware.com/cnsi/distroless/static:nonroot
# FROM projects.registry.vmware.com/cnsi/golang:1.19

FROM aquasec/trivy:0.40.0

WORKDIR /
COPY --from=builder /workspace/trivy  /home/scanner/bin/scanner-trivy
USER 65532:65532
COPY --from=builder --chmod=777 /home/scanner  /home/scanner
ENV TRIVY_VERSION=${TRIVY_VERSION}
ENV SCANNER_API_SERVER_ADDR=0.0.0.0:8080
ENV SCANNER_REDIS_URL=redis://10.168.206.138:6379

ENTRYPOINT ["/home/scanner/bin/scanner-trivy"]





