// Copyright 2022 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0
// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHealthZParams creates a new HealthZParams object
// with the default values initialized.
func NewHealthZParams() *HealthZParams {

	return &HealthZParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHealthZParamsWithTimeout creates a new HealthZParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHealthZParamsWithTimeout(timeout time.Duration) *HealthZParams {

	return &HealthZParams{

		timeout: timeout,
	}
}

// NewHealthZParamsWithContext creates a new HealthZParams object
// with the default values initialized, and the ability to set a context for a request
func NewHealthZParamsWithContext(ctx context.Context) *HealthZParams {

	return &HealthZParams{

		Context: ctx,
	}
}

// NewHealthZParamsWithHTTPClient creates a new HealthZParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHealthZParamsWithHTTPClient(client *http.Client) *HealthZParams {

	return &HealthZParams{
		HTTPClient: client,
	}
}

/*
HealthZParams contains all the parameters to send to the API endpoint
for the health z operation typically these are written to a http.Request
*/
type HealthZParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the health z params
func (o *HealthZParams) WithTimeout(timeout time.Duration) *HealthZParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the health z params
func (o *HealthZParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the health z params
func (o *HealthZParams) WithContext(ctx context.Context) *HealthZParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the health z params
func (o *HealthZParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the health z params
func (o *HealthZParams) WithHTTPClient(client *http.Client) *HealthZParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the health z params
func (o *HealthZParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HealthZParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
