// Copyright 2022 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0
// Code generated by go-swagger; DO NOT EDIT.

package assessment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/rest/models"
)

// GetNSAssessmentReader is a Reader for the GetNSAssessment structure.
type GetNSAssessmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNSAssessmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNSAssessmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetNSAssessmentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNSAssessmentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNSAssessmentOK creates a GetNSAssessmentOK with default headers values
func NewGetNSAssessmentOK() *GetNSAssessmentOK {
	return &GetNSAssessmentOK{}
}

/*
GetNSAssessmentOK handles this case with default header values.

successful operation
*/
type GetNSAssessmentOK struct {
	Payload *models.AssessmentResponse
}

func (o *GetNSAssessmentOK) Error() string {
	return fmt.Sprintf("[GET /namespaces/{ns}/assessments/{policy}][%d] getNSAssessmentOK  %+v", 200, o.Payload)
}

func (o *GetNSAssessmentOK) GetPayload() *models.AssessmentResponse {
	return o.Payload
}

func (o *GetNSAssessmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssessmentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNSAssessmentBadRequest creates a GetNSAssessmentBadRequest with default headers values
func NewGetNSAssessmentBadRequest() *GetNSAssessmentBadRequest {
	return &GetNSAssessmentBadRequest{}
}

/*
GetNSAssessmentBadRequest handles this case with default header values.

Bad request
*/
type GetNSAssessmentBadRequest struct {
}

func (o *GetNSAssessmentBadRequest) Error() string {
	return fmt.Sprintf("[GET /namespaces/{ns}/assessments/{policy}][%d] getNSAssessmentBadRequest ", 400)
}

func (o *GetNSAssessmentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetNSAssessmentInternalServerError creates a GetNSAssessmentInternalServerError with default headers values
func NewGetNSAssessmentInternalServerError() *GetNSAssessmentInternalServerError {
	return &GetNSAssessmentInternalServerError{}
}

/*
GetNSAssessmentInternalServerError handles this case with default header values.

Internal server error occurred
*/
type GetNSAssessmentInternalServerError struct {
}

func (o *GetNSAssessmentInternalServerError) Error() string {
	return fmt.Sprintf("[GET /namespaces/{ns}/assessments/{policy}][%d] getNSAssessmentInternalServerError ", 500)
}

func (o *GetNSAssessmentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
