# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
apiVersion: goharbor.goharbor.io/v1alpha1
kind: InspectionPolicy
metadata:
  name: inspectionpolicy-sample
spec:
  settingsName: sample-setting
  enabled: true
  workNamespace: cronjobs
  schedule: "*/1 * * * *"
  strategy:
    historyLimit: 5
    suspend: false
    concurrencyRule: "Forbid"
  inspector:
    image: projects.registry.vmware.com/cnsi/inspector:0.1
    imagePullPolicy: IfNotPresent
  inspection:
    namespaceSelector:
      matchLabels:
        goharbor.io/watch: "true"
    assessment:
      generate: true
      format: "YAML"
      liveTime: 3600
      managedBy: true
      elasticSearchEnabled: true
      elasticSearchAddr: "https://quickstart-es-http.default:9200"
      elasticSearchUser: "elastic" 
      elasticSearchPasswd: "QB44q12nv9dN8O0RAf84l9QT"
      elasticSearchCert: |
        -----BEGIN CERTIFICATE-----
        MIIESTCCAzGgAwIBAgIRANiiu2kPjeKjeOUuKRFkKgQwDQYJKoZIhvcNAQELBQAw
        LzETMBEGA1UECxMKcXVpY2tzdGFydDEYMBYGA1UEAxMPcXVpY2tzdGFydC1odHRw
        MB4XDTIyMTAyNjA4MTgxN1oXDTIzMTAyNjA4MjgxN1owQzETMBEGA1UECxMKcXVp
        Y2tzdGFydDEsMCoGA1UEAxMjcXVpY2tzdGFydC1lcy1odHRwLmRlZmF1bHQuZXMu
        bG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5tZm0IzqAGK6o
        C0any9oXMrB/DCzSMRgVPij/cfnHFYLqlKJmR/8Wshzo74wuK0pmKhqYUu4Af1tO
        ZBY7TMCqeLBuxp9UmrmIB6QwrcMWuGKHFwMa5V/l6BbrEOKctjwgw6D9qeKqGdY8
        1ZuTrHFnv1wXZNow//27Jx4P+jsSl/IBQjnC+zpsQNYzzZsjKijNSu16P8G1G1Vk
        asHQSpwCLuVZyjNFUarI8qEwI6gffiAzura2wecN5b16qy2rQ40GntLeCvWZ1vvd
        Zo3dhVgC4GqZylK4r6h+6swCmSgDYmoj/RHl2wgjg0/1+BOP9zYcPwG2XqssnyqC
        OAoJpuE9AgMBAAGjggFKMIIBRjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYI
        KwYBBQUHAwEGCCsGAQUFBwMCMB8GA1UdIwQYMBaAFMw0USkVpeLBvfFa8/kVihjR
        Ub6RMIHzBgNVHREEgeswgeiCI3F1aWNrc3RhcnQtZXMtaHR0cC5kZWZhdWx0LmVz
        LmxvY2FsghJxdWlja3N0YXJ0LWVzLWh0dHCCHnF1aWNrc3RhcnQtZXMtaHR0cC5k
        ZWZhdWx0LnN2Y4IacXVpY2tzdGFydC1lcy1odHRwLmRlZmF1bHSCJ3F1aWNrc3Rh
        cnQtZXMtaW50ZXJuYWwtaHR0cC5kZWZhdWx0LnN2Y4IjcXVpY2tzdGFydC1lcy1p
        bnRlcm5hbC1odHRwLmRlZmF1bHSCIyoucXVpY2tzdGFydC1lcy1kZWZhdWx0LmRl
        ZmF1bHQuc3ZjMA0GCSqGSIb3DQEBCwUAA4IBAQAfKbIqBu7simVOCS7SxAiSaV5t
        l8+eTuLQRjd296/N5g8ZNmgi+hQ9N6QURH3ovzKspDzeko5kgCb42zqWr+ZpU9xV
        MXiI7sgBneVztxDUrSYoLQP23O4UdrM9V/naV0cDxglupN5Q3tQWrbxW+sGVLTqX
        nyTpaThRC3ppjig/sXA4sfFgZtu/U1QoGpZ+Bz58vcTXoc8XRkwr0FUqHm69rTYH
        HlGVCqbETV/geKoQwY6Rxij9/MSW+l8RkFoV79srFjsvUA5/tW8hZzxIRMCEQK4/
        vzjQuCy22DFCBYgiazlfT96oChazm2bDWaXFVdaecCmfOj0ovM+gYTi6Mfmb
        -----END CERTIFICATE-----
    baselines:
      - kind: "vulnerability"
        baseline: "High"
        version: "v1.1"
        scheme: "application/vnd.security.vulnerability.report; version=1.1"
    actions:
      #- kind: "forbid_vulnerable_deployment"
      - kind: "quarantine_vulnerable_workload"
      #- kind: "alert"
